language: c
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.8.8-linux64.tar.xz
  - tar xf arduino-1.8.8-linux64.tar.xz
  - sudo mv arduino-1.8.8 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
  - ln -s $PWD /usr/local/share/arduino/libraries/Arduino-TR-064-SOAP-Library
  - arduino --pref "boardsmanager.additional.urls=https://dl.espressif.com/dl/package_esp32_index.json, http://arduino.esp8266.com/stable/package_esp8266com_index.json" --save-prefs
  - arduino --install-library ConfigManager
  - arduino --install-library ESP8266
  - arduino --install-boards esp8266:esp8266
  - arduino --install-boards esp32:esp32
script:
  - arduino --verify --board esp8266:esp6266:nodemcu $PWD/examples/home-indicator.ino
  - arduino --verify --board esp8266:esp6266:generic $PWD/examples/home-indicator.ino
  - arduino --verify --board esp32:esp32:esp32wrover $PWD/examples/home-indicator.ino
  - arduino --verify --board esp32:esp32:nodemcu-32s $PWD/examples/home-indicator.ino
  
notifications:
  email:
    on_success: change
    on_failure: change
